dev:
  - database.url: "jdbc:mysql://dev-db:3306/myapp"
    database.username: "dev_user"
    database.password: "dev_pass"
    api.timeout: 30
    feature.flag.beta: true

staging:
  - database.url: "jdbc:mysql://staging-db:3306/myapp"
    database.username: "staging_user"
    database.password: "staging_pass"
    api.timeout: 45
    feature.flag.beta: true

prod:
  - database.url: "jdbc:mysql://prod-db:3306/myapp"
    database.username: "prod_user"
    database.password: "prod_pass"
    api.timeout: 60
    feature.flag.beta: false