spring:
  data:
    redis:
      host: localhost:6381
      embedded: false
    jpa:
      url: jdbc:mariadb://localhost:3306/db1

elasticsearch:
  hosts:
    - localhost:9200
    - localhost:9300
    - localhost:9400
