database:
  url: "jdbc:mysql://prod-db:3306/myapp"
  username: "prod_user"
  password: "prod_pass"

api:
  timeout: 60
  retry: 3
  endpoints:
    - "/api/v1"
    - "/api/v2"

feature:
  flag:
    beta: false
    experimental: true

logging:
  level: INFO
  path: "/var/log/myapp"